# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto.fleetforge.v1 import scheduler_pb2 as proto_dot_fleetforge_dot_v1_dot_scheduler__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/fleetforge/v1/scheduler_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FleetSchedulerStub:
    """FleetScheduler is the worker-facing control plane (doc 1.2). Every RPC here
    is called by a worker agent talking to the gRPC control server -- nothing
    in this service is meant to be called by human/CI clients, that's the REST
    API (docs/02-openapi.yaml) instead.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterWorker = channel.unary_unary(
                '/fleetforge.v1.FleetScheduler/RegisterWorker',
                request_serializer=proto_dot_fleetforge_dot_v1_dot_scheduler__pb2.RegisterWorkerRequest.SerializeToString,
                response_deserializer=proto_dot_fleetforge_dot_v1_dot_scheduler__pb2.RegisterWorkerResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.stream_stream(
                '/fleetforge.v1.FleetScheduler/Heartbeat',
                request_serializer=proto_dot_fleetforge_dot_v1_dot_scheduler__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=proto_dot_fleetforge_dot_v1_dot_scheduler__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.ReportJobResult = channel.unary_unary(
                '/fleetforge.v1.FleetScheduler/ReportJobResult',
                request_serializer=proto_dot_fleetforge_dot_v1_dot_scheduler__pb2.ReportJobResultRequest.SerializeToString,
                response_deserializer=proto_dot_fleetforge_dot_v1_dot_scheduler__pb2.ReportJobResultResponse.FromString,
                _registered_method=True)


class FleetSchedulerServicer:
    """FleetScheduler is the worker-facing control plane (doc 1.2). Every RPC here
    is called by a worker agent talking to the gRPC control server -- nothing
    in this service is meant to be called by human/CI clients, that's the REST
    API (docs/02-openapi.yaml) instead.
    """

    def RegisterWorker(self, request, context):
        """Called once on worker-agent startup (and again on any restart). Idempotent
        on instance_id -- see docs/05-sequence-diagrams.md 5.1.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request_iterator, context):
        """Long-lived bidirectional stream, one per worker, for the lifetime of the
        agent process. Worker -> scheduler: liveness + status every 5s.
        Scheduler -> worker: job assignments, drain signals, forced re-register
        (on epoch mismatch). See docs/05-sequence-diagrams.md 5.2.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportJobResult(self, request, context):
        """Worker reports a finished (or cancelled) job. Idempotent / epoch-guarded
        per docs/05-sequence-diagrams.md 5.4 and docs/06-failure-scenarios.md #10.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FleetSchedulerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWorker,
                    request_deserializer=proto_dot_fleetforge_dot_v1_dot_scheduler__pb2.RegisterWorkerRequest.FromString,
                    response_serializer=proto_dot_fleetforge_dot_v1_dot_scheduler__pb2.RegisterWorkerResponse.SerializeToString,
            ),
            'Heartbeat': grpc.stream_stream_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=proto_dot_fleetforge_dot_v1_dot_scheduler__pb2.HeartbeatRequest.FromString,
                    response_serializer=proto_dot_fleetforge_dot_v1_dot_scheduler__pb2.HeartbeatResponse.SerializeToString,
            ),
            'ReportJobResult': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportJobResult,
                    request_deserializer=proto_dot_fleetforge_dot_v1_dot_scheduler__pb2.ReportJobResultRequest.FromString,
                    response_serializer=proto_dot_fleetforge_dot_v1_dot_scheduler__pb2.ReportJobResultResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fleetforge.v1.FleetScheduler', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fleetforge.v1.FleetScheduler', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FleetScheduler:
    """FleetScheduler is the worker-facing control plane (doc 1.2). Every RPC here
    is called by a worker agent talking to the gRPC control server -- nothing
    in this service is meant to be called by human/CI clients, that's the REST
    API (docs/02-openapi.yaml) instead.
    """

    @staticmethod
    def RegisterWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fleetforge.v1.FleetScheduler/RegisterWorker',
            proto_dot_fleetforge_dot_v1_dot_scheduler__pb2.RegisterWorkerRequest.SerializeToString,
            proto_dot_fleetforge_dot_v1_dot_scheduler__pb2.RegisterWorkerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/fleetforge.v1.FleetScheduler/Heartbeat',
            proto_dot_fleetforge_dot_v1_dot_scheduler__pb2.HeartbeatRequest.SerializeToString,
            proto_dot_fleetforge_dot_v1_dot_scheduler__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportJobResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fleetforge.v1.FleetScheduler/ReportJobResult',
            proto_dot_fleetforge_dot_v1_dot_scheduler__pb2.ReportJobResultRequest.SerializeToString,
            proto_dot_fleetforge_dot_v1_dot_scheduler__pb2.ReportJobResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
