# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/fleetforge/v1/worker.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'proto/fleetforge/v1/worker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n proto/fleetforge/v1/worker.proto\x12\rfleetforge.v1\"<\n\rResourceUsage\x12\x13\n\x0b\x63pu_percent\x18\x01 \x01(\x01\x12\x16\n\x0ememory_percent\x18\x02 \x01(\x01\"q\n\rJobAssignment\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x18\n\x10\x61ssignment_epoch\x18\x02 \x01(\x03\x12\x12\n\nrepository\x18\x03 \x01(\t\x12\x0e\n\x06\x62ranch\x18\x04 \x01(\t\x12\x12\n\ncommit_sha\x18\x05 \x01(\t*\xcc\x01\n\x0cWorkerStatus\x12\x1d\n\x19WORKER_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n\x19WORKER_STATUS_REGISTERING\x10\x01\x12\x17\n\x13WORKER_STATUS_READY\x10\x02\x12\x16\n\x12WORKER_STATUS_BUSY\x10\x03\x12\x1a\n\x16WORKER_STATUS_DRAINING\x10\x04\x12\x19\n\x15WORKER_STATUS_OFFLINE\x10\x05\x12\x16\n\x12WORKER_STATUS_DEAD\x10\x06*\xd1\x01\n\tJobStatus\x12\x1a\n\x16JOB_STATUS_UNSPECIFIED\x10\x00\x12\x15\n\x11JOB_STATUS_QUEUED\x10\x01\x12\x17\n\x13JOB_STATUS_ASSIGNED\x10\x02\x12\x16\n\x12JOB_STATUS_RUNNING\x10\x03\x12\x16\n\x12JOB_STATUS_SUCCESS\x10\x04\x12\x15\n\x11JOB_STATUS_FAILED\x10\x05\x12\x17\n\x13JOB_STATUS_RETRYING\x10\x06\x12\x18\n\x14JOB_STATUS_CANCELLED\x10\x07\x42\x44ZBgithub.com/launchverse/fleetforge/proto/fleetforge/v1;fleetforgev1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.fleetforge.v1.worker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZBgithub.com/launchverse/fleetforge/proto/fleetforge/v1;fleetforgev1'
  _globals['_WORKERSTATUS']._serialized_start=229
  _globals['_WORKERSTATUS']._serialized_end=433
  _globals['_JOBSTATUS']._serialized_start=436
  _globals['_JOBSTATUS']._serialized_end=645
  _globals['_RESOURCEUSAGE']._serialized_start=51
  _globals['_RESOURCEUSAGE']._serialized_end=111
  _globals['_JOBASSIGNMENT']._serialized_start=113
  _globals['_JOBASSIGNMENT']._serialized_end=226
# @@protoc_insertion_point(module_scope)
