// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/fleetforge/v1/scheduler.proto

package fleetforgev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FleetScheduler_RegisterWorker_FullMethodName  = "/fleetforge.v1.FleetScheduler/RegisterWorker"
	FleetScheduler_Heartbeat_FullMethodName       = "/fleetforge.v1.FleetScheduler/Heartbeat"
	FleetScheduler_ReportJobResult_FullMethodName = "/fleetforge.v1.FleetScheduler/ReportJobResult"
)

// FleetSchedulerClient is the client API for FleetScheduler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// FleetScheduler is the worker-facing control plane (doc 1.2). Every RPC here
// is called by a worker agent talking to the gRPC control server -- nothing
// in this service is meant to be called by human/CI clients, that's the REST
// API (docs/02-openapi.yaml) instead.
type FleetSchedulerClient interface {
	// Called once on worker-agent startup (and again on any restart). Idempotent
	// on instance_id -- see docs/05-sequence-diagrams.md 5.1.
	RegisterWorker(ctx context.Context, in *RegisterWorkerRequest, opts ...grpc.CallOption) (*RegisterWorkerResponse, error)
	// Long-lived bidirectional stream, one per worker, for the lifetime of the
	// agent process. Worker -> scheduler: liveness + status every 5s.
	// Scheduler -> worker: job assignments, drain signals, forced re-register
	// (on epoch mismatch). See docs/05-sequence-diagrams.md 5.2.
	Heartbeat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HeartbeatRequest, HeartbeatResponse], error)
	// Worker reports a finished (or cancelled) job. Idempotent / epoch-guarded
	// per docs/05-sequence-diagrams.md 5.4 and docs/06-failure-scenarios.md #10.
	ReportJobResult(ctx context.Context, in *ReportJobResultRequest, opts ...grpc.CallOption) (*ReportJobResultResponse, error)
}

type fleetSchedulerClient struct {
	cc grpc.ClientConnInterface
}

func NewFleetSchedulerClient(cc grpc.ClientConnInterface) FleetSchedulerClient {
	return &fleetSchedulerClient{cc}
}

func (c *fleetSchedulerClient) RegisterWorker(ctx context.Context, in *RegisterWorkerRequest, opts ...grpc.CallOption) (*RegisterWorkerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterWorkerResponse)
	err := c.cc.Invoke(ctx, FleetScheduler_RegisterWorker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetSchedulerClient) Heartbeat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HeartbeatRequest, HeartbeatResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FleetScheduler_ServiceDesc.Streams[0], FleetScheduler_Heartbeat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HeartbeatRequest, HeartbeatResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FleetScheduler_HeartbeatClient = grpc.BidiStreamingClient[HeartbeatRequest, HeartbeatResponse]

func (c *fleetSchedulerClient) ReportJobResult(ctx context.Context, in *ReportJobResultRequest, opts ...grpc.CallOption) (*ReportJobResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportJobResultResponse)
	err := c.cc.Invoke(ctx, FleetScheduler_ReportJobResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FleetSchedulerServer is the server API for FleetScheduler service.
// All implementations must embed UnimplementedFleetSchedulerServer
// for forward compatibility.
//
// FleetScheduler is the worker-facing control plane (doc 1.2). Every RPC here
// is called by a worker agent talking to the gRPC control server -- nothing
// in this service is meant to be called by human/CI clients, that's the REST
// API (docs/02-openapi.yaml) instead.
type FleetSchedulerServer interface {
	// Called once on worker-agent startup (and again on any restart). Idempotent
	// on instance_id -- see docs/05-sequence-diagrams.md 5.1.
	RegisterWorker(context.Context, *RegisterWorkerRequest) (*RegisterWorkerResponse, error)
	// Long-lived bidirectional stream, one per worker, for the lifetime of the
	// agent process. Worker -> scheduler: liveness + status every 5s.
	// Scheduler -> worker: job assignments, drain signals, forced re-register
	// (on epoch mismatch). See docs/05-sequence-diagrams.md 5.2.
	Heartbeat(grpc.BidiStreamingServer[HeartbeatRequest, HeartbeatResponse]) error
	// Worker reports a finished (or cancelled) job. Idempotent / epoch-guarded
	// per docs/05-sequence-diagrams.md 5.4 and docs/06-failure-scenarios.md #10.
	ReportJobResult(context.Context, *ReportJobResultRequest) (*ReportJobResultResponse, error)
	mustEmbedUnimplementedFleetSchedulerServer()
}

// UnimplementedFleetSchedulerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFleetSchedulerServer struct{}

func (UnimplementedFleetSchedulerServer) RegisterWorker(context.Context, *RegisterWorkerRequest) (*RegisterWorkerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterWorker not implemented")
}
func (UnimplementedFleetSchedulerServer) Heartbeat(grpc.BidiStreamingServer[HeartbeatRequest, HeartbeatResponse]) error {
	return status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedFleetSchedulerServer) ReportJobResult(context.Context, *ReportJobResultRequest) (*ReportJobResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportJobResult not implemented")
}
func (UnimplementedFleetSchedulerServer) mustEmbedUnimplementedFleetSchedulerServer() {}
func (UnimplementedFleetSchedulerServer) testEmbeddedByValue()                        {}

// UnsafeFleetSchedulerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FleetSchedulerServer will
// result in compilation errors.
type UnsafeFleetSchedulerServer interface {
	mustEmbedUnimplementedFleetSchedulerServer()
}

func RegisterFleetSchedulerServer(s grpc.ServiceRegistrar, srv FleetSchedulerServer) {
	// If the following call panics, it indicates UnimplementedFleetSchedulerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FleetScheduler_ServiceDesc, srv)
}

func _FleetScheduler_RegisterWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterWorkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetSchedulerServer).RegisterWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetScheduler_RegisterWorker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetSchedulerServer).RegisterWorker(ctx, req.(*RegisterWorkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetScheduler_Heartbeat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FleetSchedulerServer).Heartbeat(&grpc.GenericServerStream[HeartbeatRequest, HeartbeatResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FleetScheduler_HeartbeatServer = grpc.BidiStreamingServer[HeartbeatRequest, HeartbeatResponse]

func _FleetScheduler_ReportJobResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportJobResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetSchedulerServer).ReportJobResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetScheduler_ReportJobResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetSchedulerServer).ReportJobResult(ctx, req.(*ReportJobResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FleetScheduler_ServiceDesc is the grpc.ServiceDesc for FleetScheduler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FleetScheduler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fleetforge.v1.FleetScheduler",
	HandlerType: (*FleetSchedulerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterWorker",
			Handler:    _FleetScheduler_RegisterWorker_Handler,
		},
		{
			MethodName: "ReportJobResult",
			Handler:    _FleetScheduler_ReportJobResult_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Heartbeat",
			Handler:       _FleetScheduler_Heartbeat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/fleetforge/v1/scheduler.proto",
}
