// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/fleetforge/v1/scheduler.proto

package fleetforgev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterWorkerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	InstanceId    string                 `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Os            string                 `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	CpuCores      int32                  `protobuf:"varint,4,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	MemoryMb      int32                  `protobuf:"varint,5,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Capabilities  []string               `protobuf:"bytes,7,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Version       string                 `protobuf:"bytes,8,opt,name=version,proto3" json:"version,omitempty"`
	CapacitySlots int32                  `protobuf:"varint,9,opt,name=capacity_slots,json=capacitySlots,proto3" json:"capacity_slots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterWorkerRequest) Reset() {
	*x = RegisterWorkerRequest{}
	mi := &file_proto_fleetforge_v1_scheduler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkerRequest) ProtoMessage() {}

func (x *RegisterWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fleetforge_v1_scheduler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkerRequest.ProtoReflect.Descriptor instead.
func (*RegisterWorkerRequest) Descriptor() ([]byte, []int) {
	return file_proto_fleetforge_v1_scheduler_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterWorkerRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterWorkerRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *RegisterWorkerRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *RegisterWorkerRequest) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *RegisterWorkerRequest) GetMemoryMb() int32 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *RegisterWorkerRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *RegisterWorkerRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *RegisterWorkerRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterWorkerRequest) GetCapacitySlots() int32 {
	if x != nil {
		return x.CapacitySlots
	}
	return 0
}

type RegisterWorkerResponse struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	WorkerId                 string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Epoch                    int64                  `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	HeartbeatIntervalSeconds int32                  `protobuf:"varint,3,opt,name=heartbeat_interval_seconds,json=heartbeatIntervalSeconds,proto3" json:"heartbeat_interval_seconds,omitempty"`
	HeartbeatTimeoutSeconds  int32                  `protobuf:"varint,4,opt,name=heartbeat_timeout_seconds,json=heartbeatTimeoutSeconds,proto3" json:"heartbeat_timeout_seconds,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *RegisterWorkerResponse) Reset() {
	*x = RegisterWorkerResponse{}
	mi := &file_proto_fleetforge_v1_scheduler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkerResponse) ProtoMessage() {}

func (x *RegisterWorkerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fleetforge_v1_scheduler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkerResponse.ProtoReflect.Descriptor instead.
func (*RegisterWorkerResponse) Descriptor() ([]byte, []int) {
	return file_proto_fleetforge_v1_scheduler_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterWorkerResponse) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *RegisterWorkerResponse) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *RegisterWorkerResponse) GetHeartbeatIntervalSeconds() int32 {
	if x != nil {
		return x.HeartbeatIntervalSeconds
	}
	return 0
}

func (x *RegisterWorkerResponse) GetHeartbeatTimeoutSeconds() int32 {
	if x != nil {
		return x.HeartbeatTimeoutSeconds
	}
	return 0
}

type HeartbeatRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	WorkerId          string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Epoch             int64                  `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Status            WorkerStatus           `protobuf:"varint,3,opt,name=status,proto3,enum=fleetforge.v1.WorkerStatus" json:"status,omitempty"`
	CurrentJobId      *string                `protobuf:"bytes,4,opt,name=current_job_id,json=currentJobId,proto3,oneof" json:"current_job_id,omitempty"`
	ResourceUsage     *ResourceUsage         `protobuf:"bytes,5,opt,name=resource_usage,json=resourceUsage,proto3" json:"resource_usage,omitempty"`
	AvailableCapacity int32                  `protobuf:"varint,6,opt,name=available_capacity,json=availableCapacity,proto3" json:"available_capacity,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_fleetforge_v1_scheduler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fleetforge_v1_scheduler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_fleetforge_v1_scheduler_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *HeartbeatRequest) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *HeartbeatRequest) GetStatus() WorkerStatus {
	if x != nil {
		return x.Status
	}
	return WorkerStatus_WORKER_STATUS_UNSPECIFIED
}

func (x *HeartbeatRequest) GetCurrentJobId() string {
	if x != nil && x.CurrentJobId != nil {
		return *x.CurrentJobId
	}
	return ""
}

func (x *HeartbeatRequest) GetResourceUsage() *ResourceUsage {
	if x != nil {
		return x.ResourceUsage
	}
	return nil
}

func (x *HeartbeatRequest) GetAvailableCapacity() int32 {
	if x != nil {
		return x.AvailableCapacity
	}
	return 0
}

type HeartbeatResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged   bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	Assignment     *JobAssignment         `protobuf:"bytes,2,opt,name=assignment,proto3,oneof" json:"assignment,omitempty"`
	DrainRequested bool                   `protobuf:"varint,3,opt,name=drain_requested,json=drainRequested,proto3" json:"drain_requested,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_fleetforge_v1_scheduler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fleetforge_v1_scheduler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_fleetforge_v1_scheduler_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *HeartbeatResponse) GetAssignment() *JobAssignment {
	if x != nil {
		return x.Assignment
	}
	return nil
}

func (x *HeartbeatResponse) GetDrainRequested() bool {
	if x != nil {
		return x.DrainRequested
	}
	return false
}

type ReportJobResultRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	JobId           string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	AssignmentEpoch int64                  `protobuf:"varint,2,opt,name=assignment_epoch,json=assignmentEpoch,proto3" json:"assignment_epoch,omitempty"`
	Status          JobStatus              `protobuf:"varint,3,opt,name=status,proto3,enum=fleetforge.v1.JobStatus" json:"status,omitempty"`
	ExitCode        int32                  `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	LogRef          string                 `protobuf:"bytes,5,opt,name=log_ref,json=logRef,proto3" json:"log_ref,omitempty"`
	ErrorMessage    string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReportJobResultRequest) Reset() {
	*x = ReportJobResultRequest{}
	mi := &file_proto_fleetforge_v1_scheduler_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportJobResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportJobResultRequest) ProtoMessage() {}

func (x *ReportJobResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fleetforge_v1_scheduler_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportJobResultRequest.ProtoReflect.Descriptor instead.
func (*ReportJobResultRequest) Descriptor() ([]byte, []int) {
	return file_proto_fleetforge_v1_scheduler_proto_rawDescGZIP(), []int{4}
}

func (x *ReportJobResultRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ReportJobResultRequest) GetAssignmentEpoch() int64 {
	if x != nil {
		return x.AssignmentEpoch
	}
	return 0
}

func (x *ReportJobResultRequest) GetStatus() JobStatus {
	if x != nil {
		return x.Status
	}
	return JobStatus_JOB_STATUS_UNSPECIFIED
}

func (x *ReportJobResultRequest) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ReportJobResultRequest) GetLogRef() string {
	if x != nil {
		return x.LogRef
	}
	return ""
}

func (x *ReportJobResultRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ReportJobResultResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged        bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	DiscardedStaleEpoch bool                   `protobuf:"varint,2,opt,name=discarded_stale_epoch,json=discardedStaleEpoch,proto3" json:"discarded_stale_epoch,omitempty"` // true when doc 6 scenario #10 / #6 fires: this report was superseded
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ReportJobResultResponse) Reset() {
	*x = ReportJobResultResponse{}
	mi := &file_proto_fleetforge_v1_scheduler_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportJobResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportJobResultResponse) ProtoMessage() {}

func (x *ReportJobResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fleetforge_v1_scheduler_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportJobResultResponse.ProtoReflect.Descriptor instead.
func (*ReportJobResultResponse) Descriptor() ([]byte, []int) {
	return file_proto_fleetforge_v1_scheduler_proto_rawDescGZIP(), []int{5}
}

func (x *ReportJobResultResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *ReportJobResultResponse) GetDiscardedStaleEpoch() bool {
	if x != nil {
		return x.DiscardedStaleEpoch
	}
	return false
}

var File_proto_fleetforge_v1_scheduler_proto protoreflect.FileDescriptor

const file_proto_fleetforge_v1_scheduler_proto_rawDesc = "" +
	"\n" +
	"#proto/fleetforge/v1/scheduler.proto\x12\rfleetforge.v1\x1a proto/fleetforge/v1/worker.proto\"\x88\x03\n" +
	"\x15RegisterWorkerRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x12\x0e\n" +
	"\x02os\x18\x03 \x01(\tR\x02os\x12\x1b\n" +
	"\tcpu_cores\x18\x04 \x01(\x05R\bcpuCores\x12\x1b\n" +
	"\tmemory_mb\x18\x05 \x01(\x05R\bmemoryMb\x12H\n" +
	"\x06labels\x18\x06 \x03(\v20.fleetforge.v1.RegisterWorkerRequest.LabelsEntryR\x06labels\x12\"\n" +
	"\fcapabilities\x18\a \x03(\tR\fcapabilities\x12\x18\n" +
	"\aversion\x18\b \x01(\tR\aversion\x12%\n" +
	"\x0ecapacity_slots\x18\t \x01(\x05R\rcapacitySlots\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc5\x01\n" +
	"\x16RegisterWorkerResponse\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x03R\x05epoch\x12<\n" +
	"\x1aheartbeat_interval_seconds\x18\x03 \x01(\x05R\x18heartbeatIntervalSeconds\x12:\n" +
	"\x19heartbeat_timeout_seconds\x18\x04 \x01(\x05R\x17heartbeatTimeoutSeconds\"\xac\x02\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x03R\x05epoch\x123\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1b.fleetforge.v1.WorkerStatusR\x06status\x12)\n" +
	"\x0ecurrent_job_id\x18\x04 \x01(\tH\x00R\fcurrentJobId\x88\x01\x01\x12C\n" +
	"\x0eresource_usage\x18\x05 \x01(\v2\x1c.fleetforge.v1.ResourceUsageR\rresourceUsage\x12-\n" +
	"\x12available_capacity\x18\x06 \x01(\x05R\x11availableCapacityB\x11\n" +
	"\x0f_current_job_id\"\xb2\x01\n" +
	"\x11HeartbeatResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12A\n" +
	"\n" +
	"assignment\x18\x02 \x01(\v2\x1c.fleetforge.v1.JobAssignmentH\x00R\n" +
	"assignment\x88\x01\x01\x12'\n" +
	"\x0fdrain_requested\x18\x03 \x01(\bR\x0edrainRequestedB\r\n" +
	"\v_assignment\"\xe7\x01\n" +
	"\x16ReportJobResultRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12)\n" +
	"\x10assignment_epoch\x18\x02 \x01(\x03R\x0fassignmentEpoch\x120\n" +
	"\x06status\x18\x03 \x01(\x0e2\x18.fleetforge.v1.JobStatusR\x06status\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCode\x12\x17\n" +
	"\alog_ref\x18\x05 \x01(\tR\x06logRef\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\"q\n" +
	"\x17ReportJobResultResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x122\n" +
	"\x15discarded_stale_epoch\x18\x02 \x01(\bR\x13discardedStaleEpoch2\xa5\x02\n" +
	"\x0eFleetScheduler\x12]\n" +
	"\x0eRegisterWorker\x12$.fleetforge.v1.RegisterWorkerRequest\x1a%.fleetforge.v1.RegisterWorkerResponse\x12R\n" +
	"\tHeartbeat\x12\x1f.fleetforge.v1.HeartbeatRequest\x1a .fleetforge.v1.HeartbeatResponse(\x010\x01\x12`\n" +
	"\x0fReportJobResult\x12%.fleetforge.v1.ReportJobResultRequest\x1a&.fleetforge.v1.ReportJobResultResponseBDZBgithub.com/launchverse/fleetforge/proto/fleetforge/v1;fleetforgev1b\x06proto3"

var (
	file_proto_fleetforge_v1_scheduler_proto_rawDescOnce sync.Once
	file_proto_fleetforge_v1_scheduler_proto_rawDescData []byte
)

func file_proto_fleetforge_v1_scheduler_proto_rawDescGZIP() []byte {
	file_proto_fleetforge_v1_scheduler_proto_rawDescOnce.Do(func() {
		file_proto_fleetforge_v1_scheduler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_fleetforge_v1_scheduler_proto_rawDesc), len(file_proto_fleetforge_v1_scheduler_proto_rawDesc)))
	})
	return file_proto_fleetforge_v1_scheduler_proto_rawDescData
}

var file_proto_fleetforge_v1_scheduler_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_fleetforge_v1_scheduler_proto_goTypes = []any{
	(*RegisterWorkerRequest)(nil),   // 0: fleetforge.v1.RegisterWorkerRequest
	(*RegisterWorkerResponse)(nil),  // 1: fleetforge.v1.RegisterWorkerResponse
	(*HeartbeatRequest)(nil),        // 2: fleetforge.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),       // 3: fleetforge.v1.HeartbeatResponse
	(*ReportJobResultRequest)(nil),  // 4: fleetforge.v1.ReportJobResultRequest
	(*ReportJobResultResponse)(nil), // 5: fleetforge.v1.ReportJobResultResponse
	nil,                             // 6: fleetforge.v1.RegisterWorkerRequest.LabelsEntry
	(WorkerStatus)(0),               // 7: fleetforge.v1.WorkerStatus
	(*ResourceUsage)(nil),           // 8: fleetforge.v1.ResourceUsage
	(*JobAssignment)(nil),           // 9: fleetforge.v1.JobAssignment
	(JobStatus)(0),                  // 10: fleetforge.v1.JobStatus
}
var file_proto_fleetforge_v1_scheduler_proto_depIdxs = []int32{
	6,  // 0: fleetforge.v1.RegisterWorkerRequest.labels:type_name -> fleetforge.v1.RegisterWorkerRequest.LabelsEntry
	7,  // 1: fleetforge.v1.HeartbeatRequest.status:type_name -> fleetforge.v1.WorkerStatus
	8,  // 2: fleetforge.v1.HeartbeatRequest.resource_usage:type_name -> fleetforge.v1.ResourceUsage
	9,  // 3: fleetforge.v1.HeartbeatResponse.assignment:type_name -> fleetforge.v1.JobAssignment
	10, // 4: fleetforge.v1.ReportJobResultRequest.status:type_name -> fleetforge.v1.JobStatus
	0,  // 5: fleetforge.v1.FleetScheduler.RegisterWorker:input_type -> fleetforge.v1.RegisterWorkerRequest
	2,  // 6: fleetforge.v1.FleetScheduler.Heartbeat:input_type -> fleetforge.v1.HeartbeatRequest
	4,  // 7: fleetforge.v1.FleetScheduler.ReportJobResult:input_type -> fleetforge.v1.ReportJobResultRequest
	1,  // 8: fleetforge.v1.FleetScheduler.RegisterWorker:output_type -> fleetforge.v1.RegisterWorkerResponse
	3,  // 9: fleetforge.v1.FleetScheduler.Heartbeat:output_type -> fleetforge.v1.HeartbeatResponse
	5,  // 10: fleetforge.v1.FleetScheduler.ReportJobResult:output_type -> fleetforge.v1.ReportJobResultResponse
	8,  // [8:11] is the sub-list for method output_type
	5,  // [5:8] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_fleetforge_v1_scheduler_proto_init() }
func file_proto_fleetforge_v1_scheduler_proto_init() {
	if File_proto_fleetforge_v1_scheduler_proto != nil {
		return
	}
	file_proto_fleetforge_v1_worker_proto_init()
	file_proto_fleetforge_v1_scheduler_proto_msgTypes[2].OneofWrappers = []any{}
	file_proto_fleetforge_v1_scheduler_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_fleetforge_v1_scheduler_proto_rawDesc), len(file_proto_fleetforge_v1_scheduler_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_fleetforge_v1_scheduler_proto_goTypes,
		DependencyIndexes: file_proto_fleetforge_v1_scheduler_proto_depIdxs,
		MessageInfos:      file_proto_fleetforge_v1_scheduler_proto_msgTypes,
	}.Build()
	File_proto_fleetforge_v1_scheduler_proto = out.File
	file_proto_fleetforge_v1_scheduler_proto_goTypes = nil
	file_proto_fleetforge_v1_scheduler_proto_depIdxs = nil
}
