// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/fleetforge/v1/worker.proto

package fleetforgev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Mirrors the `worker_status` Postgres enum (docs/03-database-schema.md) --
// keep these two definitions in lockstep by hand for now; a codegen check
// that diffs them is a reasonable later addition, not a foundational one.
type WorkerStatus int32

const (
	WorkerStatus_WORKER_STATUS_UNSPECIFIED WorkerStatus = 0 // never used on the wire; catches a missing field vs. an explicit state
	WorkerStatus_WORKER_STATUS_REGISTERING WorkerStatus = 1
	WorkerStatus_WORKER_STATUS_READY       WorkerStatus = 2
	WorkerStatus_WORKER_STATUS_BUSY        WorkerStatus = 3
	WorkerStatus_WORKER_STATUS_DRAINING    WorkerStatus = 4
	WorkerStatus_WORKER_STATUS_OFFLINE     WorkerStatus = 5
	WorkerStatus_WORKER_STATUS_DEAD        WorkerStatus = 6
)

// Enum value maps for WorkerStatus.
var (
	WorkerStatus_name = map[int32]string{
		0: "WORKER_STATUS_UNSPECIFIED",
		1: "WORKER_STATUS_REGISTERING",
		2: "WORKER_STATUS_READY",
		3: "WORKER_STATUS_BUSY",
		4: "WORKER_STATUS_DRAINING",
		5: "WORKER_STATUS_OFFLINE",
		6: "WORKER_STATUS_DEAD",
	}
	WorkerStatus_value = map[string]int32{
		"WORKER_STATUS_UNSPECIFIED": 0,
		"WORKER_STATUS_REGISTERING": 1,
		"WORKER_STATUS_READY":       2,
		"WORKER_STATUS_BUSY":        3,
		"WORKER_STATUS_DRAINING":    4,
		"WORKER_STATUS_OFFLINE":     5,
		"WORKER_STATUS_DEAD":        6,
	}
)

func (x WorkerStatus) Enum() *WorkerStatus {
	p := new(WorkerStatus)
	*p = x
	return p
}

func (x WorkerStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkerStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_fleetforge_v1_worker_proto_enumTypes[0].Descriptor()
}

func (WorkerStatus) Type() protoreflect.EnumType {
	return &file_proto_fleetforge_v1_worker_proto_enumTypes[0]
}

func (x WorkerStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkerStatus.Descriptor instead.
func (WorkerStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_fleetforge_v1_worker_proto_rawDescGZIP(), []int{0}
}

type JobStatus int32

const (
	JobStatus_JOB_STATUS_UNSPECIFIED JobStatus = 0
	JobStatus_JOB_STATUS_QUEUED      JobStatus = 1
	JobStatus_JOB_STATUS_ASSIGNED    JobStatus = 2
	JobStatus_JOB_STATUS_RUNNING     JobStatus = 3
	JobStatus_JOB_STATUS_SUCCESS     JobStatus = 4
	JobStatus_JOB_STATUS_FAILED      JobStatus = 5
	JobStatus_JOB_STATUS_RETRYING    JobStatus = 6
	JobStatus_JOB_STATUS_CANCELLED   JobStatus = 7
)

// Enum value maps for JobStatus.
var (
	JobStatus_name = map[int32]string{
		0: "JOB_STATUS_UNSPECIFIED",
		1: "JOB_STATUS_QUEUED",
		2: "JOB_STATUS_ASSIGNED",
		3: "JOB_STATUS_RUNNING",
		4: "JOB_STATUS_SUCCESS",
		5: "JOB_STATUS_FAILED",
		6: "JOB_STATUS_RETRYING",
		7: "JOB_STATUS_CANCELLED",
	}
	JobStatus_value = map[string]int32{
		"JOB_STATUS_UNSPECIFIED": 0,
		"JOB_STATUS_QUEUED":      1,
		"JOB_STATUS_ASSIGNED":    2,
		"JOB_STATUS_RUNNING":     3,
		"JOB_STATUS_SUCCESS":     4,
		"JOB_STATUS_FAILED":      5,
		"JOB_STATUS_RETRYING":    6,
		"JOB_STATUS_CANCELLED":   7,
	}
)

func (x JobStatus) Enum() *JobStatus {
	p := new(JobStatus)
	*p = x
	return p
}

func (x JobStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_fleetforge_v1_worker_proto_enumTypes[1].Descriptor()
}

func (JobStatus) Type() protoreflect.EnumType {
	return &file_proto_fleetforge_v1_worker_proto_enumTypes[1]
}

func (x JobStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobStatus.Descriptor instead.
func (JobStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_fleetforge_v1_worker_proto_rawDescGZIP(), []int{1}
}

type ResourceUsage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuPercent    float64                `protobuf:"fixed64,1,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryPercent float64                `protobuf:"fixed64,2,opt,name=memory_percent,json=memoryPercent,proto3" json:"memory_percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceUsage) Reset() {
	*x = ResourceUsage{}
	mi := &file_proto_fleetforge_v1_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceUsage) ProtoMessage() {}

func (x *ResourceUsage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fleetforge_v1_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceUsage.ProtoReflect.Descriptor instead.
func (*ResourceUsage) Descriptor() ([]byte, []int) {
	return file_proto_fleetforge_v1_worker_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceUsage) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *ResourceUsage) GetMemoryPercent() float64 {
	if x != nil {
		return x.MemoryPercent
	}
	return 0
}

// What the scheduler pushes to a worker once a job is assigned to it.
// (doc 5.4 / doc 2 JobAssignment schema)
type JobAssignment struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	JobId           string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	AssignmentEpoch int64                  `protobuf:"varint,2,opt,name=assignment_epoch,json=assignmentEpoch,proto3" json:"assignment_epoch,omitempty"`
	Repository      string                 `protobuf:"bytes,3,opt,name=repository,proto3" json:"repository,omitempty"`
	Branch          string                 `protobuf:"bytes,4,opt,name=branch,proto3" json:"branch,omitempty"`
	CommitSha       string                 `protobuf:"bytes,5,opt,name=commit_sha,json=commitSha,proto3" json:"commit_sha,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *JobAssignment) Reset() {
	*x = JobAssignment{}
	mi := &file_proto_fleetforge_v1_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobAssignment) ProtoMessage() {}

func (x *JobAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fleetforge_v1_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobAssignment.ProtoReflect.Descriptor instead.
func (*JobAssignment) Descriptor() ([]byte, []int) {
	return file_proto_fleetforge_v1_worker_proto_rawDescGZIP(), []int{1}
}

func (x *JobAssignment) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobAssignment) GetAssignmentEpoch() int64 {
	if x != nil {
		return x.AssignmentEpoch
	}
	return 0
}

func (x *JobAssignment) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *JobAssignment) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *JobAssignment) GetCommitSha() string {
	if x != nil {
		return x.CommitSha
	}
	return ""
}

var File_proto_fleetforge_v1_worker_proto protoreflect.FileDescriptor

const file_proto_fleetforge_v1_worker_proto_rawDesc = "" +
	"\n" +
	" proto/fleetforge/v1/worker.proto\x12\rfleetforge.v1\"W\n" +
	"\rResourceUsage\x12\x1f\n" +
	"\vcpu_percent\x18\x01 \x01(\x01R\n" +
	"cpuPercent\x12%\n" +
	"\x0ememory_percent\x18\x02 \x01(\x01R\rmemoryPercent\"\xa8\x01\n" +
	"\rJobAssignment\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12)\n" +
	"\x10assignment_epoch\x18\x02 \x01(\x03R\x0fassignmentEpoch\x12\x1e\n" +
	"\n" +
	"repository\x18\x03 \x01(\tR\n" +
	"repository\x12\x16\n" +
	"\x06branch\x18\x04 \x01(\tR\x06branch\x12\x1d\n" +
	"\n" +
	"commit_sha\x18\x05 \x01(\tR\tcommitSha*\xcc\x01\n" +
	"\fWorkerStatus\x12\x1d\n" +
	"\x19WORKER_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19WORKER_STATUS_REGISTERING\x10\x01\x12\x17\n" +
	"\x13WORKER_STATUS_READY\x10\x02\x12\x16\n" +
	"\x12WORKER_STATUS_BUSY\x10\x03\x12\x1a\n" +
	"\x16WORKER_STATUS_DRAINING\x10\x04\x12\x19\n" +
	"\x15WORKER_STATUS_OFFLINE\x10\x05\x12\x16\n" +
	"\x12WORKER_STATUS_DEAD\x10\x06*\xd1\x01\n" +
	"\tJobStatus\x12\x1a\n" +
	"\x16JOB_STATUS_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11JOB_STATUS_QUEUED\x10\x01\x12\x17\n" +
	"\x13JOB_STATUS_ASSIGNED\x10\x02\x12\x16\n" +
	"\x12JOB_STATUS_RUNNING\x10\x03\x12\x16\n" +
	"\x12JOB_STATUS_SUCCESS\x10\x04\x12\x15\n" +
	"\x11JOB_STATUS_FAILED\x10\x05\x12\x17\n" +
	"\x13JOB_STATUS_RETRYING\x10\x06\x12\x18\n" +
	"\x14JOB_STATUS_CANCELLED\x10\aBDZBgithub.com/launchverse/fleetforge/proto/fleetforge/v1;fleetforgev1b\x06proto3"

var (
	file_proto_fleetforge_v1_worker_proto_rawDescOnce sync.Once
	file_proto_fleetforge_v1_worker_proto_rawDescData []byte
)

func file_proto_fleetforge_v1_worker_proto_rawDescGZIP() []byte {
	file_proto_fleetforge_v1_worker_proto_rawDescOnce.Do(func() {
		file_proto_fleetforge_v1_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_fleetforge_v1_worker_proto_rawDesc), len(file_proto_fleetforge_v1_worker_proto_rawDesc)))
	})
	return file_proto_fleetforge_v1_worker_proto_rawDescData
}

var file_proto_fleetforge_v1_worker_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_fleetforge_v1_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_fleetforge_v1_worker_proto_goTypes = []any{
	(WorkerStatus)(0),     // 0: fleetforge.v1.WorkerStatus
	(JobStatus)(0),        // 1: fleetforge.v1.JobStatus
	(*ResourceUsage)(nil), // 2: fleetforge.v1.ResourceUsage
	(*JobAssignment)(nil), // 3: fleetforge.v1.JobAssignment
}
var file_proto_fleetforge_v1_worker_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_fleetforge_v1_worker_proto_init() }
func file_proto_fleetforge_v1_worker_proto_init() {
	if File_proto_fleetforge_v1_worker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_fleetforge_v1_worker_proto_rawDesc), len(file_proto_fleetforge_v1_worker_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_fleetforge_v1_worker_proto_goTypes,
		DependencyIndexes: file_proto_fleetforge_v1_worker_proto_depIdxs,
		EnumInfos:         file_proto_fleetforge_v1_worker_proto_enumTypes,
		MessageInfos:      file_proto_fleetforge_v1_worker_proto_msgTypes,
	}.Build()
	File_proto_fleetforge_v1_worker_proto = out.File
	file_proto_fleetforge_v1_worker_proto_goTypes = nil
	file_proto_fleetforge_v1_worker_proto_depIdxs = nil
}
